-- This file is autogenerated out of the Settings/SettingsDefinition.lua file. 
-- For permanent changes, use this file and regenerate the Config.lua file. 

---@class Config
Config = {
    
	-- TRACE 
	DebugTracePaths = false,			-- Shows the trace line and search area from Commo Rose selection 
	WaypointRange = 50,					-- Set how far away waypoints are visible (meters) 
	DrawWaypointLines = true,			-- Draw waypoint connection lines 
	LineRange = 25,						-- Set how far away waypoint lines are visible (meters) 
	DrawWaypointIDs = true,				-- Draw the IDs of the waypoints 
	TextRange = 7,						-- Set how far away waypoint text is visible (meters) 
	DrawSpawnPoints = false,			-- Draw the Points where players can spawn 
	SpawnPointRange = 100,				-- Set how far away spawn points are visible (meters) 
	TraceDelta = 0.3,					-- Update interval of trace 
	NodesPerCycle = 400,				-- Set how many nodes get drawn per cycle. Affects performance 

	-- OTHER 
	DisableUserInterface = false,		-- If true, the complete UI will be disabled (not available in the UI) 
	DisableChatCommands = false,		-- If true, no chat commands can be used 
	DisableRCONCommands = false,		-- If true, no RCON commands can be used 
	IgnorePermissions = false,			-- If true, all permissions are ignored --> everyone can do everything 
	Language = nil,						-- de_DE as sample (default is English, when language file does not exist) 
} 
