local code = 'en_EN' -- This file is autogenerated!

-- GENERAL

-- DIFFICULTY

-- SPAWN

-- SPAWN LIMITS

-- BEHAVIOUR

-- VEHICLE

-- WEAPONS

-- TRACE

-- ADVANCED

-- EXPERT

-- OTHER

-- Strings of ext/Client/ClientNodeEditor.lua

-- Strings of ext/Server/BotSpawner.lua

-- Strings of ext/Server/UIServer.lua

-- Strings of ext/Server/NodeCollection.lua
